add gitpod-io/dazzle-util

diff --git a/full/Dockerfile b/full/Dockerfile
--- a/full/Dockerfile
+++ b/full/Dockerfile
@@ -283,11 +283,22 @@ RUN . /home/gitpod/.nix-profile/etc/profile.d/nix.sh \
 
 # only for x86_64
 # ## Prologue (built across all layers) ###
-# LABEL dazzle/layer=dazzle-prologue
-# LABEL dazzle/test=tests/prologue.yaml
-# USER root
-# RUN curl -o /usr/bin/dazzle-util -fsSL https://github.com/csweichel/dazzle/releases/download/v0.0.3/dazzle-util_0.0.3_Linux_x86_64 \
-#     && chmod +x /usr/bin/dazzle-util
+LABEL dazzle/layer=dazzle-prologue
+LABEL dazzle/test=tests/prologue.yaml
+USER root
+RUN arch="$(uname -m)"; \
+	url=; \
+	case "$arch" in \
+		'x86_64') \
+			export ARCH='x86_64' \
+			;; \
+		'aarch64') \
+			export ARCH='arm64' \
+			;; \
+		*) echo >&2 "error: unsupported architecture '$arch'"; exit 1 ;; \
+	esac; \
+    curl -o /usr/bin/dazzle-util -fsSL https://github.com/gitpod-io/dazzle/releases/download/v0.1.6/dazzle-util_0.1.6_Linux_${ARCH} \
+    && chmod +x /usr/bin/dazzle-util
 # # merge dpkg status files
 # RUN cp /var/lib/dpkg/status /tmp/dpkg-status \
 #     && for i in $(ls /var/lib/apt/dazzle-marks/*.status); do /usr/bin/dazzle-util debian dpkg-status-merge /tmp/dpkg-status $i > /tmp/dpkg-status; done \
